export const DEMO_DATA = {
  blog: {
    content: `The 5 AI Tools That Actually Changed How I Work\n\nI spent six months testing every AI productivity tool I could find. Most were noise. A few genuinely changed how I work. Here's what survived the cut — and why.\n\n## The Problem With Most AI Tools\n\nEveryone's selling you a 10x productivity multiplier. The reality? Most AI tools automate tasks you didn't actually need to do in the first place. The ones worth keeping automate the friction between your ideas and your output.\n\n## 1. Automated Research Synthesis\n\nThe biggest time sink in knowledge work isn't doing the work — it's getting up to speed. AI-powered research synthesis cuts hours of reading into a 10-minute briefing. The key is learning to give it a sharp question, not a vague topic.\n\n## 2. First-Draft Generation\n\nNot for finished work. For breaking the blank page. A rough AI draft that's 60% wrong is still faster to edit than starting from zero. The editing mindset is fundamentally different from the creation mindset — and faster.\n\n## 3. Meeting Transcript Analysis\n\nThe hidden goldmine. Every meeting produces a transcript. AI can pull action items, key decisions, and follow-up questions in under a minute. This alone saved me roughly 3 hours a week.\n\n## 4. Code Explanation and Debugging\n\nEven if you're not an engineer, understanding what code does is increasingly valuable. AI explanations in plain English have made me significantly better at working with technical teams.\n\n## 5. Personalized Learning Paths\n\nInstead of generic courses, I now ask AI to build me a 30-minute daily curriculum on whatever I'm trying to learn. More targeted, faster, and I retain more because it connects to real problems I'm solving.\n\n## Key Takeaways\n\n- The best AI tools remove friction, not work itself\n- Start with one tool and use it deeply before adding more\n- The quality of your prompts determines 80% of the output quality\n- AI handles the draft; your judgment handles the final call\n- Measure time saved weekly, or you won't know what's working`,
    meta: '523 words · 3 min read',
  },
  twitter: {
    content: `1/ I tested 50+ AI productivity tools over 6 months.\n\nOnly 5 actually changed how I work.\n\nHere's what survived (and why most failed):\n\n2/ Most AI tools fail because they automate tasks you didn't need to do anyway.\n\nThe winners automate the friction between your ideas and your output.\n\nBig difference.\n\n3/ Tool #1: Research synthesis\n\nGetting up to speed is the real time sink — not the work itself.\n\nAI briefings cut hours of reading into 10 minutes.\n\nRule: Give it a sharp question, not a vague topic.\n\n4/ Tool #2: First-draft generation\n\nNot for finished work. For breaking the blank page.\n\nA 60% wrong AI draft is still faster to edit than starting from zero.\n\nEditing is faster than creating. Always.\n\n5/ Tool #3: Meeting transcript analysis\n\nEvery meeting = a transcript.\nEvery transcript = action items, decisions, follow-ups.\n\nAI pulls all of it in under a minute.\n\nThis alone saved me 3 hours/week.\n\n6/ Tool #4: Code explanation\n\nYou don't need to be an engineer.\n\nBut understanding what code does? Increasingly valuable.\n\nAI plain-English explanations made me dramatically better at working with technical teams.\n\n7/ Tool #5: Personalized learning paths\n\nInstead of generic courses → ask AI to build a 30-min daily curriculum on your specific problem.\n\nMore targeted. Faster. Better retention.\n\n8/ The meta-lesson:\n\nAI quality = prompt quality.\n\n80% of what you get out is determined by what you put in.\n\nLearn to prompt well, and every tool gets 2x better overnight.\n\n#AI #Productivity #Tools`,
    meta: '8 tweets · ready to post',
  },
  linkedin: {
    content: `I wasted 3 months on AI tools that didn't matter.\n\nHere's what I wish someone told me earlier.\n\nNot all AI productivity tools are equal. Most automate things you didn't need to do in the first place.\n\nThe ones that actually moved the needle for me did one thing: they removed the friction between my ideas and my output.\n\nSpecifically:\n- Research synthesis (hours → minutes)\n- First-draft generation (blank page → rough draft in 3 minutes)\n- Meeting transcript analysis (saved ~3 hours/week immediately)\n\nThe pattern? None of them replaced my judgment. They all just got me to the point where my judgment was needed, faster.\n\nThe mistake I see people make: trying 10 tools at once, using each one lightly, and concluding "AI isn't that useful yet."\n\nPick one. Use it deeply for 30 days. Learn its limits.\n\nThat's when the real leverage shows up.\n\nWhich AI tool has actually changed how you work? Curious what's working for people in this space.`,
    meta: '1,021 characters',
  },
  email: {
    content: `Subject: The 5 AI tools I actually kept\n\nHey,\n\nI've been testing AI productivity tools obsessively for the past six months. Not reviewing them — actually using them in real work, every day, and measuring what happened.\n\nMost didn't survive. Here's what did, and why it matters for you:\n\n**Research synthesis** is the biggest unlock. Getting up to speed on a topic used to eat hours. Now it takes minutes, if you give the AI a sharp question instead of a vague topic.\n\n**First-draft generation** isn't for finished work — it's for breaking the blank page. A rough draft you can edit is always faster than starting cold.\n\n**Meeting transcripts** turned out to be the hidden goldmine. Every meeting produces a transcript. AI extracts action items and decisions in under a minute. I got 3 hours back in my first week.\n\nThe through-line: none of these replaced my judgment. They all accelerated getting to the point where my judgment was needed.\n\nIf you're going to try one thing: pick a single tool, commit to it for 30 days, and learn its edges. That's when the real leverage shows up.\n\nMore next week,\nJ`,
    meta: '198 words · subject line included',
  },
  quotes: {
    content: `## 5 Most Quotable Lines\n\n1. "Most AI tools automate tasks you didn't actually need to do in the first place."\n2. "The best AI tools remove friction between your ideas and your output — not the work itself."\n3. "A rough AI draft that's 60% wrong is still faster to edit than starting from zero."\n4. "The quality of your prompts determines 80% of what you get back."\n5. "AI handles the draft. Your judgment handles the final call."\n\n## 3 Social Media Hooks\n\n1. I tested 50 AI tools. Only 5 survived. Here's the filter I used.\n2. The AI tool that saved me 3 hours a week wasn't ChatGPT. It was my meeting transcripts.\n3. Stop using AI to automate work. Start using it to eliminate the friction before the work.\n\n## 3 Controversial or Debatable Takeaways\n\n1. Most people using AI are automating the wrong things — and getting busier, not more productive.\n2. Prompt quality matters more than tool choice. A great prompter with a basic tool beats a bad prompter with the best tool.\n3. AI learning paths will eventually make structured courses obsolete for self-directed learners.\n\n## 1 One-Line Summary\n\nThe AI tools worth keeping are the ones that eliminate friction, not the ones that replace your thinking.`,
    meta: '5 quotes · 3 hooks · 3 takeaways',
  },
  reels: {
    content: `## Caption\nMost people try 10 AI tools and feel more overwhelmed than before. I tested 50+ and only kept 5. Here's the exact list that actually changed my workflow.\n\nSave this before you waste another month on the wrong tools.\n\n#AI #Productivity #AITools #WorkSmarter #ContentCreator #TechTips #Automation\n\n## 3 Video Hooks\n1. "I deleted 45 AI tools from my workflow last month — here's the 5 that stayed."\n2. "Stop using AI to get busier. Use it to remove the friction before the real work starts."\n3. "The most valuable AI tool I found isn't ChatGPT — and it's completely free."\n\n## 3 On-Screen Text Ideas\n1. "I tested 50+ AI tools so you don't have to"\n2. "Only 5 survived. Here's why."\n3. "The filter that changed everything"\n\n## 30-Second Script Outline\n• Hook: Open with the deletion line — "I removed 45 AI tools last month. Here's the 5 that survived."\n• Problem: Most people use AI to automate tasks they didn't actually need to do — they get busier, not better.\n• Insight: The tools worth keeping all do one thing: remove the friction between your ideas and your output.\n• Proof: One tool alone — meeting transcript analysis — gave me 3 hours back in the first week.\n• CTA: Drop a comment with the one AI tool you swear by — I'll tell you if it made my list.`,
    meta: 'caption + hooks + script · reels ready',
  },
  notionUrl: null,
};
